Bug fix for Boto configuration overrides
I was wondering why the test coverage of the S3 cache backend had
declined so significantly when I noticed that the tests on Travis CI
exposed a bug I hadn't ran into so far:

    Traceback (most recent call last):
      File "/home/travis/build/paylogic/pip-accel/pip_accel/caches/__init__.py", line 157, in get
        pathname = backend.get(filename)
      File "/home/travis/build/paylogic/pip-accel/pip_accel/caches/s3.py", line 147, in get
        key = self.s3_bucket.get_key(raw_key)
      File "/home/travis/build/paylogic/pip-accel/pip_accel/caches/s3.py", line 214, in s3_bucket
        self.cached_bucket = self.s3_connection.get_bucket(self.config.s3_cache_bucket)
      File "/home/travis/build/paylogic/pip-accel/pip_accel/caches/s3.py", line 254, in s3_connection
        boto.config.add_section('Boto')
      File "/opt/python/2.6.9/lib/python2.6/ConfigParser.py", line 245, in add_section
        raise DuplicateSectionError(section)
    DuplicateSectionError: Section 'Boto' already exists

    (from https://travis-ci.org/paylogic/pip-accel/jobs/61020251)

I'm guessing this is caused by the fact that Travis CI installs a Boto
configuration file. These changes (Boto configuration overrides) were
introduced in pip-accel 0.27.1 (6d33a6edcd8).